tap "puma/puma"
tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/services"
tap "github/bootstrap"
brew "ack"
brew "autoconf"
brew "coreutils"
brew "gdbm"
brew "gnupg"
brew "go"
brew "python"
brew "grc"
brew "hub"
brew "imagemagick"
brew "jp2a"
brew "jq"
brew "launch_socket_server", restart_service: true
brew "launchdns", restart_service: true
brew "libcaca", args: ["with-imlib2"]
brew "libgit2"
brew "mysql", restart_service: true
brew "netcdf"
brew "nginx", restart_service: true
brew "node"
brew "node-build"
brew "nodenv"
brew "phantomjs"
brew "pinentry-mac"
brew "postgresql", restart_service: true
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: true
brew "roundup"
brew "spaceman-diff"
brew "spark"
brew "unrar"
brew "wget"
brew "wine"
brew "yarn"
brew "puma/puma/puma-dev"
